name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

        # Installation des dépendances locales
      - name: Install gpsUtil.jar
        run: mvn install:install-file -Dfile=TourGuide/libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar

      - name: Install tripPricer.jar
        run: mvn install:install-file -Dfile=TourGuide/libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar

      - name: Install rewardCentral.jar
        run: mvn install:install-file -Dfile=TourGuide/libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar 

      - name: Compile the project
        run: |
          cd TourGuide
          mvn clean compile
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Run tests
        run: mvn test
  package:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Package the application
        run: |
          cd TourGuide
          mvn package -DskipTests
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: application-jar
          path: TourGuide/target/*.jar
